//
// MIT License
// Copyright Pawel Krzywdzinski
//

using System.Text;
using Microsoft.CodeAnalysis;

namespace SlimObservable.Generator
{
    /// <summary>
    /// Pure emitter: takes an ObservableClassModel and produces text.
    /// No access to ISymbol / Compilation at all, which means this step
    /// does not have to run when the model has not changed.
    /// </summary>
    internal class ObservableClassGenerator
    {
        readonly ObservableClassModel model;

        StringBuilder builder;

        public ObservableClassGenerator(ObservableClassModel model)
        {
            this.model = model;
        }

        public void Build(SourceProductionContext context)
        {
            builder = new StringBuilder();

            builder.AppendLine("//");
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//");
            builder.AppendLine();

            builder.AppendLine("#nullable disable");
            builder.AppendLine();

            GenerateClassNamespace();

            builder.AppendLine();
            builder.AppendLine("#nullable restore");

            context.AddSource($"{model.Namespace}.{model.FileName}.g.cs", builder.ToString());
        }

        void GenerateClassNamespace()
        {
            builder.AppendLine($@"
using SlimObservable;

namespace {model.Namespace}
{{
    public partial class {model.SymbolName} : System.ComponentModel.INotifyPropertyChanged
	{{");
            GenerateClassBody();
            builder.AppendLine($@"
    }}
}}");
        }

        void GenerateClassBody()
        {
            GeneratePropertyChanged();
            GenerateProperties();
        }

        void GeneratePropertyChanged()
        {
            builder.AppendLine($@"
        public {(model.PropertyChangedExistsInBases ? "new " : "")}event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void InvokePropertyChanged(string propertyName)
        {{
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }}
        ");
        }

        // --------------------------------------
        // ---- generate observable properties ----
        // --------------------------------------

        void GenerateProperties()
        {
            if (model.Properties.Count > 0)
                builder.AppendLine($@"
        // ----- properties -----");

            foreach (var property in model.Properties)
                GeneratePropertyForField(property);
        }

        void GeneratePropertyForField(ObservablePropertyModel property)
        {
            var name = property.Name;
            var camelcaseName = property.CamelCaseName;
            var typeName = property.TypeName;

            var callback = property.CallbackName == null ?

                    $@"_{camelcaseName} = value;
                    InvokePropertyChanged(nameof({name}));"

                    :

                    @$"
                    var callbackArgs = new PropertyCallbackArgs<{typeName}>(""{name}"", _{camelcaseName}, value);
                    {property.CallbackName}(this, callbackArgs);
                    if (callbackArgs.NewValue != callbackArgs.OldValue)
                    {{
                        _{camelcaseName} = callbackArgs.NewValue;
                        InvokePropertyChanged(nameof({name}));
                    }}";

            builder.Append($@"
        private {typeName} _{camelcaseName} = {(property.DefaultValueString != null ? $"({typeName}){property.DefaultValueString}" : $"default({typeName})")};
        public {typeName} {name}
        {{
            get {{ return _{camelcaseName}; }}
            set
            {{
                if (_{camelcaseName} != value)
                {{                    
                    {callback}
                }}
            }}
        }}");
        }
    }
}
